### PR TITLE
SDC-Docker Authentication

### PR DESCRIPTION
**Pull request by 13W**

### CODE REVIEW

**Comment by cachafla** [comment]
Looks good to me but the commit is missing the updated package.json that includes the keyapi dependency.

**Comment by dan-luk** [comment]
hey Andres, can we please have that merged?  Thanks

**Comment by trentm** [comment]
The first two commits were cherry-picked into master in commit 04cdffc81794af2eeb26ffeda92aeede771ecbce and commit 1e88805dae6ae611386fa9490298d3efbc558f4c. Then I cleaned up auth and hooked up token auth in commit 8d4fa8a0fd8a780bd31be65d08ea76ceeda73520 (DOCKER-210). Thanks.

**Comment by trentm** [comment]
Regarding the admin interface/port change: I've created DOCKER-211 for that.

**Comment by dan-luk** [comment]
thanks Trent.

**Pull request closed without merging**
